# Site settings
description: Promoção Tadeu Santigado te da um carro.
baseurl: ""
url: ""

# User settings
username: Tadeu Santiago

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
